import { BreadcrumbItem, CarouselItem, Category, MerchantData } from "@/types";

import { CouponData } from "@/components/hive/merchant/coupon";

// Flash Sale Item interface
export interface FlashSaleItem {
  id: string;
  title: string;
  currentPrice: number;
  originalPrice: number;
  currency: string;
  localCurrency: string;
  localPrice: number;
  totalItems: number;
  remainingItems: number;
  image: string;
  discountPercentage: number;
  expiryTime: string;
  category: string;
}

export const nearbyRestaurants = [
  {
    id: 1,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.9,
    category: "Category",
    location: "Location",
  },
  {
    id: 2,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.9,
    category: "Category",
    location: "Location",
  },
  {
    id: 3,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.9,
    category: "Category",
    location: "Location",
  },
  {
    id: 4,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.9,
    category: "Category",
    location: "Location",
  },
  {
    id: 5,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.9,
    category: "Category",
    location: "Location",
  },
];

export const bestDealRestaurants = [
  {
    id: 6,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.8,
    category: "Deals",
    location: "Location",
  },
  {
    id: 7,
    image: "/assets/food.png",
    name: "Special Offers",
    rating: 4.7,
    category: "Discounts",
    location: "Location",
  },
  {
    id: 8,
    image: "/assets/food.png",
    name: "Value Meals",
    rating: 4.9,
    category: "Budget",
    location: "Location",
  },
  {
    id: 9,
    image: "/assets/food.png",
    name: "Happy Hour",
    rating: 4.6,
    category: "Drinks",
    location: "Location",
  },
  {
    id: 20,
    image: "/assets/food.png",
    name: "Happy Hour",
    rating: 4.6,
    category: "Drinks",
    location: "Location",
  },
  {
    id: 22,
    image: "/assets/food.png",
    name: "Happy Hour",
    rating: 4.6,
    category: "Drinks",
    location: "Location",
  },
  {
    id: 23,
    image: "/assets/food.png",
    name: "Happy Hour",
    rating: 4.6,
    category: "Drinks",
    location: "Location",
  },
];

export const forYouRestaurants = [
  {
    id: 10,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.9,
    category: "Popular",
    location: "Location",
  },
  {
    id: 11,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.8,
    category: "Cuisine",
    location: "Location",
  },
  {
    id: 12,
    image: "/assets/food.png",
    name: "Trending Now",
    rating: 4.7,
    category: "Trending",
    location: "Location",
  },
  {
    id: 13,
    image: "/assets/food.png",
    name: "Must Try",
    rating: 4.9,
    category: "Featured",
    location: "Location",
  },
  {
    id: 14,
    image: "/assets/food.png",
    name: "Must Try",
    rating: 4.9,
    category: "Featured",
    location: "Location",
  },
  {
    id: 15,
    image: "/assets/food.png",
    name: "Must Try",
    rating: 4.9,
    category: "Featured",
    location: "Location",
  },
  {
    id: 16,
    image: "/assets/food.png",
    name: "Must Try",
    rating: 4.9,
    category: "Featured",
    location: "Location",
  },
];

// Hero-specific carousel with default data
export const heroCarouselImages: CarouselItem[] = [
  {
    id: 1,
    image: "/fake/merchant-slide.png",
    alt: "Asian cuisine selection",
  },
  {
    id: 3,
    image: "/fake/merchant-slide.png",
    alt: "Traditional Cambodian dishes",
  },
  {
    id: 4,
    image: "/fake/merchant-slide.png",
    alt: "Cocktails and appetizers",
  },
];

// Sample coupon data
export const merchantCoupons: CouponData[] = [
  {
    id: "coup1",
    discount: "$5",
    minSpend: "$50",
    title: "Buy from $50, apply code to WIN $5",
    description: "Get $5 off when you spend $50 or more",
    expiryDate: "2025-07-01",
    code: "SAVE5",
    type: "discount",
    isExpired: false,
    isUsed: false,
  },
  {
    id: "coup2",
    discount: "$10",
    minSpend: "$100",
    title: "Big Savings on Large Orders",
    description: "Save $10 when you order $100 or more",
    expiryDate: "2025-06-15",
    code: "BIG10",
    type: "discount",
    isExpired: false,
    isUsed: false,
  },
  {
    id: "coup3",
    discount: "20%",
    minSpend: "$25",
    title: "Weekend Special Discount",
    description: "20% off on weekend orders",
    expiryDate: "2025-05-30",
    code: "WEEKEND20",
    type: "discount",
    isExpired: false,
    isUsed: false,
  },
  {
    id: "coup4",
    discount: "$3",
    minSpend: "$30",
    title: "First Time Customer Bonus",
    description: "Welcome offer for new customers",
    expiryDate: "2024-12-31",
    code: "WELCOME3",
    type: "discount",
    isExpired: true,
    isUsed: false,
  },
  {
    id: "coup5",
    discount: "$15",
    minSpend: "$150",
    title: "Family Feast Deal",
    description: "Perfect for family orders",
    expiryDate: "2025-08-01",
    code: "FAMILY15",
    type: "discount",
    isExpired: false,
    isUsed: true,
  },
];

// Mock merchant data
export const merchantData: MerchantData = {
  name: "Burger King BKK",
  category: "Fastfood",
  rating: 4.9,
  address: "257 Rue Pasteur No. 51, Phnom Penh, Cambodia",
  heroImage: "/fake/merchant-cover.png",
  logo: "/fake/merchant-logo.png",
  status: "Open",
  closingTime: "11 PM",
};

// Menu categories
export const categories: Category[] = [
  { id: "All", label: "All", count: 45 },
  { id: "Recommended", label: "Recommended", count: 12 },
  { id: "Beef Burger", label: "Beef Burger", count: 8 },
  { id: "Chicken Burger", label: "Chicken Burger", count: 6 },
  { id: "Family Combo", label: "Family Combo", count: 4 },
  { id: "Fried Chicken", label: "Fried Chicken", count: 7 },
  { id: "Happy Meals", label: "Happy Meals", count: 3 },
  { id: "Ice-Blended", label: "Ice-Blended", count: 5 },
  { id: "Snacks", label: "Snacks", count: 8 },
  { id: "Tea", label: "Tea", count: 2 },
];

// Breadcrumb navigation items
export const breadcrumbItems: BreadcrumbItem[] = [
  { label: "Home", href: "/" },
  { label: "Burger King", href: "/restaurants" },
  { label: "Burger King BKK", active: true },
];

// Flash Sale Items - Perfect for creating flash sale sections
export const flashSaleItems: FlashSaleItem[] = [
  {
    id: "flash1",
    title: "Big Mac Combo Meal",
    currentPrice: 8.99,
    originalPrice: 12.99,
    currency: "$",
    localCurrency: "៛",
    localPrice: 36000,
    totalItems: 100,
    remainingItems: 23,
    image: "/fake/promotions.png",
    discountPercentage: 31,
    expiryTime: "6d 10h 46m 5s",
    category: "Combo Meals",
  },
  {
    id: "flash2",
    title: "Crispy Chicken Deluxe",
    currentPrice: 6.5,
    originalPrice: 9.99,
    currency: "$",
    localCurrency: "៛",
    localPrice: 26000,
    totalItems: 80,
    remainingItems: 12,
    image: "/fake/promotions.png",
    discountPercentage: 35,
    expiryTime: "5d 8h 22m 15s",
    category: "Chicken",
  },
  {
    id: "flash3",
    title: "Double Cheese Supreme",
    currentPrice: 7.25,
    originalPrice: 11.5,
    currency: "$",
    localCurrency: "៛",
    localPrice: 29000,
    totalItems: 60,
    remainingItems: 8,
    image: "/fake/promotions.png",
    discountPercentage: 37,
    expiryTime: "4d 15h 33m 42s",
    category: "Burgers",
  },
  {
    id: "flash4",
    title: "Fish Fillet Special",
    currentPrice: 5.99,
    originalPrice: 8.75,
    currency: "$",
    localCurrency: "៛",
    localPrice: 24000,
    totalItems: 120,
    remainingItems: 67,
    image: "/fake/promotions.png",
    discountPercentage: 32,
    expiryTime: "7d 2h 18m 30s",
    category: "Fish",
  },
  {
    id: "flash5",
    title: "Spicy Wings Bucket",
    currentPrice: 12.99,
    originalPrice: 18.99,
    currency: "$",
    localCurrency: "៛",
    localPrice: 52000,
    totalItems: 50,
    remainingItems: 15,
    image: "/fake/promotions.png",
    discountPercentage: 32,
    expiryTime: "3d 12h 5m 18s",
    category: "Chicken",
  },
  {
    id: "flash6",
    title: "Veggie Burger Classic",
    currentPrice: 4.75,
    originalPrice: 7.25,
    currency: "$",
    localCurrency: "៛",
    localPrice: 19000,
    totalItems: 90,
    remainingItems: 45,
    image: "/fake/promotions.png",
    discountPercentage: 34,
    expiryTime: "6d 20h 12m 8s",
    category: "Vegetarian",
  },
  {
    id: "flash7",
    title: "BBQ Bacon Deluxe",
    currentPrice: 9.5,
    originalPrice: 13.99,
    currency: "$",
    localCurrency: "៛",
    localPrice: 38000,
    totalItems: 70,
    remainingItems: 3,
    image: "/fake/promotions.png",
    discountPercentage: 32,
    expiryTime: "2d 6h 45m 12s",
    category: "BBQ",
  },
  {
    id: "flash8",
    title: "Family Pizza Deal",
    currentPrice: 15.99,
    originalPrice: 24.99,
    currency: "$",
    localCurrency: "៛",
    localPrice: 64000,
    totalItems: 40,
    remainingItems: 18,
    image: "/fake/promotions.png",
    discountPercentage: 36,
    expiryTime: "5d 14h 28m 55s",
    category: "Pizza",
  },
  {
    id: "flash9",
    title: "Ice Cream Sundae",
    currentPrice: 2.99,
    originalPrice: 4.5,
    currency: "$",
    localCurrency: "៛",
    localPrice: 12000,
    totalItems: 150,
    remainingItems: 89,
    image: "/fake/promotions.png",
    discountPercentage: 34,
    expiryTime: "8d 3h 17m 22s",
    category: "Desserts",
  },
  {
    id: "flash10",
    title: "Loaded Nachos Supreme",
    currentPrice: 6.75,
    originalPrice: 10.25,
    currency: "$",
    localCurrency: "៛",
    localPrice: 27000,
    totalItems: 85,
    remainingItems: 52,
    image: "/fake/promotions.png",
    discountPercentage: 34,
    expiryTime: "4d 9h 31m 44s",
    category: "Snacks",
  },
  {
    id: "flash11",
    title: "Breakfast Burrito Combo",
    currentPrice: 5.25,
    originalPrice: 7.99,
    currency: "$",
    localCurrency: "៛",
    localPrice: 21000,
    totalItems: 75,
    remainingItems: 28,
    image: "/fake/promotions.png",
    discountPercentage: 34,
    expiryTime: "1d 16h 42m 11s",
    category: "Breakfast",
  },
  {
    id: "flash12",
    title: "Chocolate Milkshake",
    currentPrice: 3.5,
    originalPrice: 5.25,
    currency: "$",
    localCurrency: "៛",
    localPrice: 14000,
    totalItems: 100,
    remainingItems: 71,
    image: "/fake/promotions.png",
    discountPercentage: 33,
    expiryTime: "6d 11h 55m 33s",
    category: "Beverages",
  },
];
