export const nearbyRestaurants = [
  {
    id: 1,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.9,
    category: "Category",
    location: "Location",
  },
  {
    id: 2,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.9,
    category: "Category",
    location: "Location",
  },
  {
    id: 3,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.9,
    category: "Category",
    location: "Location",
  },
  {
    id: 4,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.9,
    category: "Category",
    location: "Location",
  },
  {
    id: 5,
    image: "/assets/food.png",
    name: "Merchant Name",
    rating: 4.9,
    category: "Category",
    location: "Location",
  },
];

export const bestDealRestaurants = [
  {
    id: 6,
    image: "/assets/food.png",
    name: "Best Deal Restaurant",
    rating: 4.8,
    category: "Deals",
    location: "Location",
  },
  {
    id: 7,
    image: "/assets/food.png",
    name: "Special Offers",
    rating: 4.7,
    category: "Discounts",
    location: "Location",
  },
  {
    id: 8,
    image: "/assets/food.png",
    name: "Value Meals",
    rating: 4.9,
    category: "Budget",
    location: "Location",
  },
  {
    id: 9,
    image: "/assets/food.png",
    name: "Happy Hour",
    rating: 4.6,
    category: "Drinks",
    location: "Location",
  },
  {
    id: 20,
    image: "/assets/food.png",
    name: "Happy Hour",
    rating: 4.6,
    category: "Drinks",
    location: "Location",
  },
  {
    id: 22,
    image: "/assets/food.png",
    name: "Happy Hour",
    rating: 4.6,
    category: "Drinks",
    location: "Location",
  },
  {
    id: 23,
    image: "/assets/food.png",
    name: "Happy Hour",
    rating: 4.6,
    category: "Drinks",
    location: "Location",
  },
];

export const forYouRestaurants = [
  {
    id: 10,
    image: "/assets/food.png",
    name: "Recommended Choice",
    rating: 4.9,
    category: "Popular",
    location: "Location",
  },
  {
    id: 11,
    image: "/assets/food.png",
    name: "Your Favorite",
    rating: 4.8,
    category: "Cuisine",
    location: "Location",
  },
  {
    id: 12,
    image: "/assets/food.png",
    name: "Trending Now",
    rating: 4.7,
    category: "Trending",
    location: "Location",
  },
  {
    id: 13,
    image: "/assets/food.png",
    name: "Must Try",
    rating: 4.9,
    category: "Featured",
    location: "Location",
  },
  {
    id: 14,
    image: "/assets/food.png",
    name: "Must Try",
    rating: 4.9,
    category: "Featured",
    location: "Location",
  },
  {
    id: 15,
    image: "/assets/food.png",
    name: "Must Try",
    rating: 4.9,
    category: "Featured",
    location: "Location",
  },
  {
    id: 16,
    image: "/assets/food.png",
    name: "Must Try",
    rating: 4.9,
    category: "Featured",
    location: "Location",
  },
];
