type OutletInfoResponse = {
  status: boolean;
  message: string;
  data: {
    approved: number;
    id: number;
    merchant_id: number;
    status: number;
    name: string;
    address: {
      address: string;
      district: string;
      ward: string;
      city: string;
    };
    latitude: string;
    longitude: string;
    open_hour: string;
    close_hour: string;
    use_working_hours: number;
    working_hours: {
      mon: { order: number; close: boolean; time_interval: string };
      tue: { order: number; close: boolean; time_interval: string };
      wed: { order: number; close: boolean; time_interval: string };
      thu: { order: number; close: boolean; time_interval: string };
      fri: { order: number; close: boolean; time_interval: string };
      sat: { order: number; close: boolean; time_interval: string };
      sun: { order: number; close: boolean; time_interval: string };
    };
    contactless_temporarily_closed: number;
    contactless_closed_from: string | null;
    contactless_closed_to: string | null;
    contactless_last_order_time: string | null;
    temporarily_closed_from: string | null;
    temporarily_closed_to: string | null;
    tolerance_radius: number;
    tolerance_time: number;
    onboard_at: string | null;
    deactive_at: string | null;
    terminated_at: string | null;
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
    is_franchise: number;
    mca: string;
    phone: string;
    delivery_note: string;
    parking_fee: string | null;
    city_key: string;
    province_id: number;
    district_id: number;
    ward_id: number;
    address_detail: string;
    short_name: string;
    available_time_id: number | null;
    storeCd: string | null;
    outlet_images: {
      id: number;
      status: number;
      image_path: string;
      image_name: string;
      created_at: string;
    }[];
    outlet_roles: {
      id: number;
      role: number;
      limit_login_from: string | null;
      limit_login_to: string | null;
      limit_login_area: string | null;
      status: number;
      created_at: string;
      updated_at: string;
      deleted_at: string | null;
    }[];
    merchant: {
      approved: number;
      allow_invite_friend: number;
      language: string;
      id: number;
      status: number;
      name: string;
      short_name: string;
      email: string;
      mca: string;
      address: {
        city: string;
        ward: string;
        address: string;
        district: string;
        address_detail: string;
      };
      phone: string;
      logo_path: string;
      logo_image: string;
      fanpage: string;
      website: string;
      introduction: string;
      tax_code: string;
      company_name: string;
      company_address: string;
      beneficiary: string;
      bank_account: string;
      bank_name: string;
      bank_branch: string;
      onboard_at: string | null;
      deactive_at: string | null;
      terminated_at: string | null;
      created_at: string;
      updated_at: string;
      deleted_at: string | null;
      zalo_notification: boolean;
      pay_by_cash_fee_percentage: number | null;
      redeem_svd_fee_percentage: number | null;
      redeem_voucher_fee_percentage: number | null;
      transaction_reward_percentage: number | null;
      max_transaction_reward_value: number | null;
      menus: any[];
      hidden: boolean;
      merchant_group_id: number | null;
      apply_contactless_pay_by_cash: number;
      merchant_type: string;
      enable_custom_menu_show_time: number;
      allow_contactless_guest_user: number;
      recent_origin_language: string | null;
      preferred_language: string | null;
      translated_characters: number;
      sub_domain: string;
      show_take_away_orders_page: number;
      enable_order_distribution: number;
      approved_menu: number;
      package_code: string | null;
      sale_code: string | null;
      province_id: number;
      district_id: number;
      ward_id: number | null;
      address_detail: string;
      sentEmailsMonthlyCount: number;
      businessType: string;
      merchantOwnerName: string;
      delivery_program: {
        id: number;
        merchant_id: number;
        name: string;
        image_name: string;
        max_cashback: number | null;
        cashback_percent: number;
        system_fee_percent: number | null;
        extra_fee_percent: number;
        fixed_cashback_first_time: number;
        status: number;
        secret: number;
        service_fee_based_on: string;
        created_at: string;
        updated_at: string;
        allow_cod: number;
        cod_extra_service_fee: number;
        enable_eta: boolean;
        eta_time: number;
        isEnableSelfPickUp: boolean;
        isEnableSelfDelivery: boolean;
        maxDistance: number;
        shippingFeeRanges: any[];
        selfPickupReminderTime: number | null;
        isAgreementShippingFeeWithCustomer: boolean;
      };
      contactless_program: {
        id: number;
        status: number;
        merchant_id: number;
        max_cashback: number;
        cashback_percent: number;
        system_fee_percent: number | null;
        first_time_reward_percent: number;
        service_charge_percent: number;
        service_fee_based_on: string;
        maximum_reward_amount: number;
        allow_contactless_guest_user: number;
        created_at: string;
        updated_at: string;
        pay_by_cash_service_fee_pct: number;
      };
    };
    district_tag: string | null;
    province_detail: { id: number; name: string; name_en: string };
    district_detail: {
      id: number;
      name: string;
      name_en: string;
      province_id: number;
    };
    ward_detail: {
      id: number;
      name: string;
      name_en: string;
      district_id: number;
    };
    available_times: any;
    joined_delivery: boolean;
    isEnableSelfPickUp: boolean;
    isEnableSelfDelivery: boolean;
    temporarily_closed: boolean;
    is_opening: boolean;
    categories: {
      id: number;
      name: string;
      status: number;
      image_path: string | null;
      image_name: string | null;
      created_at: string;
      updated_at: string;
      deleted_at: string | null;
      position: number;
    }[];
    distance: number;
    old_address: string | null;
    liked: boolean;
    fifty_percent_reward_program: any;
    isBelongsToCircleKMerchant: boolean;
    isBelongsToSevenElevenMerchant: boolean;
    enableTableBooking: boolean;
    enableMarketingProgram: boolean;
    numberOfDeals: number;
    numberOfStampDeals: number;
    formatted_working_hours: {
      day: string;
      order: number;
      close: boolean;
      time_interval: string;
    }[];
    service_charge_percent: number;
    joinedContactlessProgram: boolean;
    joined_contactless: boolean;
  };
};

type OutletBannerResponse = {
  status: boolean;
  data: [
    {
      id: number;
      name: string;
      image: string;
      image_en: string;
      status: string;
      action_link_web: string;
      action_link_app: string | null;
      platform: string;
      type: string;
      outlet_id: string | null;
      merchant_id: number;
      created_at: string;
      updated_at: string;
      deleted_at: string | null;
    },
  ];
};
